A = EMPLEATS{NUM_EMPL->NUM_EMPL2, NOM_EMPL->NOM_EMPL2, SOU->SOU2, CIUTAT_EMPL->CIUTAT_EMPL2, NUM_DPT->NUM_DPT2, NUM_PROJ->NUM_PROJ2}
B = EMPLEATS[CIUTAT_EMPL <> CIUTAT_EMPL2, NUM_EMPL <> NUM_EMPL2, NUM_DPT = NUM_DPT2]A
C = B*DEPARTAMENTS
R = C[NUM_DPT, NOM_DPT]